coverage:
  status:
    project: true
    patch: true
flags:
  node:
    paths:
      - "src/main/java/org/algomonster/datastructures/Node.java"
  linkedlist:
    paths:
      - "src/main/java/org/algomonster/datastructures/linkedlist/LinkedList.java"
  hashmap:
    paths:
      - "src/main/java/org/algomonster/datastructures/map/HashMap.java"
  array:
    paths:
      - "src/main/java/org/algomonster/datastructures/array/Array.java"
  queue:
    paths:
      - "src/main/java/org/algomonster/datastructures/queue/Queue.java"
  stack:
    paths:
      - "src/main/java/org/algomonster/datastructures/stack/Stack.java"
parsers:
  jacoco:
    partials: true