name: Maven CI - Run Tests on Push

on:
  push:
    branches:
      - main  # Trigger on pushes to main (change to your branch if needed, e.g., master or doubly)

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # GitHub's Linux runner - fast and free

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Fetches your repo code

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'  # Match your project's JDK (check pom.xml or IntelliJ Settings > Build > Compiler > Java Compiler)
          distribution: 'temurin'  # Eclipse Temurin JDK - reliable for Maven
          cache: maven  # Caches dependencies for faster runs

      - name: Build with Maven
        run: mvn clean install  # Cleans and builds your project (optional, but ensures compile before test)

      - name: Run tests
        run: mvn test  # Runs your JUnit tests (e.g., LinkedListTest)

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq  # Ensure jq is available for JSON parsing

      - name: Parse Per-Class Test Stats
        run: |
          echo "[]" > test-summary.json  # Init empty array
          shopt -s nullglob  # Handle no files without error
          for report in target/surefire-reports/*.xml; do
            if [ -f "$report" ]; then
              class=$(basename "$report" .xml | sed 's/TEST-//g' | sed 's/org.algomonster.datastructures.linkedlist.//')  # Clean class name, remove package if needed
              total=$(grep -c "<testcase" "$report" || echo 0)
              failures=$(grep -c "<failure" "$report" || echo 0)
              errors=$(grep -c "<error" "$report" || echo 0)
              skipped=$(grep -c "<skipped" "$report" || echo 0)
              echo "Debug: class=$class total=$total failures=$failures errors=$errors skipped=$skipped"  # Debug to log
              if [ "$total" -gt 0 ]; then  # Skip if no tests to avoid syntax error
                passed=$(( ${total:-0} - ${failures:-0} - ${errors:-0} - ${skipped:-0} ))  # Use defaults and wrap to force evaluation
              else
                passed=0
              fi
              jq -c --arg class "$class" --arg passed "$passed" --arg total "$total" '. + [{"class": $class, "passed": $passed, "total": $total}]' test-summary.json > tmp.json && mv tmp.json test-summary.json
            fi
          done
          if [ -s test-summary.json ] && [ "$(cat test-summary.json)" != "[]" ]; then
            echo "Generated test-summary.json with data"
          else
            echo "[{\"class\": \"NoTests\", \"passed\": \"0\", \"total\": \"0\"}]" > test-summary.json  # Default for no tests
            echo "No test reports found, generated default JSON"
          fi
          cat test-summary.json  # Debug: Print to log

      - name: Commit and Amend Test Summary
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull origin main --rebase
          git add test-summary.json
          git commit --amend --no-edit || echo "No changes to amend"
          git push origin main --force-with-lease
